spring:
  application:
    name: authentication-service
  profiles:
    active: default
  config:
    import: optional:docker.env[.properties]

  security:
    user:
      password: ${SECURITY_DEFAULT_PASSWORD}

  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092

jwt-secret: ${JWT_SECRET}
